site_name: Vera
repo_url: https://github.com/project-vera/vera-aws
repo_name: project-vera
nav:
  - Mission: index.md
  - Blogs:
    - "[02-06-2026] No More Manual Mocks.": blogs/cloudemu/cloudemu.md
    - "[02-06-2026] Can AI Agents Replace DevOps?": blogs/cloudagent/cloudagent.md
  - AWS EC2 Emulator: vera-aws.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: black
      font:
        text: Roboto
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: white
      font:
        text: Roboto
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
